
version: 1

before:
  hooks:
    - go mod tidy

builds:
  - id: zeroward
    main: ./main.go
    binary: zeroward
    flags:
      - -mod=vendor
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    
    ldflags:
      - -a -installsuffix cgo
      - -X main.gitTag={{.Tag}} -X main.gitCommit={{.Commit}} -X main.gitBranch={{.Branch}}
    env:
      - CGO_ENABLED=0
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
          {{- if eq .Arch "arm64"}}CC=aarch64-apple-darwin20.2-clang{{- end }}
        {{- end }}
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
        {{- end }}
        {{- if eq .Os "linux" }}
          {{- if eq .Arch "arm64" }}CC=aarch64-linux-gnu-gcc{{- end }}
        {{- end }}
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
      - goarm: mips64
      - gomips: hardfloat
      - goamd64: v4


archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'
    files:
      - README.md
      - LICENSE


checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{.ShortCommit}}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - 'README'
      - Merge pull request
      - Merge branch

release:
  prerelease: auto

universal_binaries:
  - # ID of resulting universal binary.
    replace: true

nfpms:
- maintainer: Abdi Omar Ousleyeh <martelluiz@gmail.com>
  description: zero knowledge encryption command line for securing files on the cloud storage
  homepage: https://github.com/Abdiooa/zeroward/
  package_name: zeroward
  license: Apache
  formats:
    - deb
    - apk

brews:
- 
  name: zeroward
  homepage: https://github.com/Abdiooa/homebrew-tools
  repository:
    - name: homebrew-tools
      owner: Abdiooa
  commit_author:
    name: Abdi Omar Ousleyeh
    email: martelluiz@gmail.com
  license: "Apache"